### ISSUE TITLE
java.lang.RuntimeException: Specified area is outside for original image

### ISSUE THREAD

**Issue by valermor** [galenframework/galen#105] opened 2014-10-02 12:03 UTC
Issue appears when parsing image comparison specs.
Occurring on Windows 7, using ChromeDriver.
Test execution generates an empty report.

**Comment by lo1tuma** [comment] 2015-10-27 11:45
I still get this error, using galen 2.1.2 on mac os X with firefox 41.0.2

**Comment by hypery2k** [comment] 2015-10-27 12:09
did you use the build-in selenium? Did you use maven?

**Comment by lo1tuma** [comment] 2015-10-27 12:21
Yes, I use the build-in selenium and I don’t use maven.

I’ve tried it with different macbook and I didn’t get the error, so I looked for what is different between those two machines. It turns out that the one macbook (where the tests work) has a retina resolution and the other one has a resolution of 1280 x 800. I reduced the resolution of the retina macbook to 1280 x 800 and I got the same exception `java.lang.RuntimeException: Specified area is outside for original image`.

**Comment by lo1tuma** [comment] 2015-10-27 16:06
So I investigated further and it seems like the resolution is not the problem. It always works on retina displays and always fails on other displays (I’ve tried it with an external monitor with a resolution of `1920x1200`).

I’ve added some debug `println`s [here](https://github.com/galenframework/galen/blob/db5eebf787d83096022515fc96bf9b30702ed269/galen-rainbow4j/src/main/java/com/galenframework/rainbow4j/Rainbow4J.java#L60)

The output is:

```
areaA.width 360
areaA.x 0
imageA.getWidth() 360
areaA.height 603
areaA.y 947
imageA.getHeight() 1549
->      image file dump.png, error 1%
->      :   java.lang.RuntimeException: Specified area is outside for original image
```

So it seems like the `areaA` is `1px` outside of `imageA`. First I thought this might be a problem using relative sizes in css (i.e. `rem`), but I’ve created `dump.png` on the same display using the galen page dump feature.

**Comment by lo1tuma** [comment] 2015-10-27 16:11
Maybe this bugfix causes the problem https://github.com/galenframework/galen/pull/311. If I understand it correctly images can be cropped during the page dump, but they are not cropped during the image comparison.

**Comment by ishubin** [comment] 2015-10-30 15:49
@lo1tuma Thanks for your investigation and for such detailed info. I will reopen this issue and will assign it to current release just so that I don't miss it once I get more time. Right now I don't have enough time to code but hope in a week or two will get back to it.

**Comment by timoreimann** [comment] 2015-11-10 16:21
@lo1tuma and I had a closer look at the issue at hand and noticed that there is already a `crop-if-outside` parameter that upon enabling fixes the problem. It wasn't mentioned in the documentation, however, which is why we just filed a pull request.

It still feels somewhat inconsistent that the image is cropped automatically during the dump but requires an explicit parameter to be set for image comparison. Maybe a different PR should try to make the behavior more consistent.

Thanks.

**Comment by ishubin** [comment] 2015-11-10 20:45
@timoreimann @lo1tuma thanks for finding that undocumented property and for pull request! I have already updated the website. Just somehow missed this one when was writing documentation.

I agree with you. It does look inconsistent. I still think that we should leave the property "crop-if-outside" disabled by default because I want to make sure that a user notices that there is a problem with getting image for a page element. If elements area is a bit outside of actual screenshot - that is a problem and we should not hide it by cropping the image. On the other hand it should not fail with stupid exception. 

What if that missing area will be filled with black pixels? This way the image validation would not be interrupted by exception and at the same time a user will notice what is going on on image comparison popup in html report.

**Comment by timoreimann** [comment] 2015-11-11 11:31
I'd first like to understand why we exactly experience the problem at hand. Is this a "natural" rounding issue which just needs to be dealt with? Or is it possible related to different rounding/calculation implementations in Galen (or a library its using for that purpose) and JS?

If it's the latter, then I'd opt for an effort to match the two implementations. Unfortunately, my understanding of Galen isn't too deep to make an assessment in this regards. Can you possibly shed some light on this, @ishubin?

**Comment by ishubin** [comment] 2015-11-12 20:41
@timoreimann If it is only about 1 pixel then I guess rounding issue is a good candidate for blaming. The way it works is pretty simple in Galen - it just uses Selenium to get the actual location of element via https://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/WebElement.html#getLocation(). 
And for getting the screenshot from a browser it again uses Selenium via https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/TakesScreenshot.html#getScreenshotAs-org.openqa.selenium.OutputType-

Also there is a custom js-based implementation in Galen (might be undocumented) https://github.com/galenframework/galen/blob/96aaa297ea80f20a140816c032346fad302e5664/galen-core/src/main/java/com/galenframework/page/selenium/AreaFinder.java#L41. It is only used in case you declare this property in your config file 
```
galen.browser.pageElement.areaFinder=jsbased
```
That property is needed in case you want to test layout in iPhone & iPod iOS 9.0. For some reason on these devices Selenium gives incorrect locations, so switching to custom js-based implementation helps in that case. 

That's pretty much about it.

**Comment by timoreimann** [comment] 2015-11-13 18:20
@ishubin Thanks for the details. The Selenium implementation just returns `int`s, while the JS approach seems to provide floating-point precision. (At least the `getBoundingClientRect()` function does.) The results are stored in a `Rect` instance, however, which returns integers again.

To me it seems that we could provide a higher-precision approach through the JS implementation if we managed to carry over the floating-point results into the Java space. WDYT?

**Comment by ishubin** [comment] 2015-11-17 09:07
@timoreimann I am not sure about that. I first want to trace and debug this issue so I can see where it goes wrong. Do you have any examples (reproducing the issue) by the way so I can play with it?

**Comment by lo1tuma** [comment] 2015-11-17 13:49
[Here is a jsfiddle](https://jsfiddle.net/nc0prtss/) where the `width` of both inner elements is floating point number.

![screen shot 2015-11-17 at 14 48 48](https://cloud.githubusercontent.com/assets/169170/11213081/563b49ee-8d3a-11e5-9ea8-f910794f655c.png)

**Comment by ishubin** [comment] 2015-11-18 09:18
@lo1tuma  I tried to reproduce this issue on Mac OS X in Firefox but it works fine for me. I adapted your code a bit code:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
        * {
            margin: 0;
        }
        .tested {
            height: 50px;
        }
    </style>
</head>
<body>
    <div style="width:899px">
        <div class="tested" id="element-2" style="width:67%; background: green; float: left;">bar</div>
        <div class="tested" id="element-1" style="width:33%; background: red; float: right;">foo</div>
    </div>
</body>
</html>
```

And for testing 

```
@objects
    element-1           #element-1
    element-2           #element-2


= Main section =
    element-1:
        image file element-1.png

    element-2:
        image file element-2.png
```

I have created page dump and reused the generated image samples for image validation

If I check the generated images then I get this:
    - layout-1-screenshot.png: PNG image data, 899 x 495, 8-bit/color RGBA, non-interlaced
    - element-1.png: PNG image data, 297 x 50, 8-bit/color RGBA, non-interlaced
    - element-2.png: PNG image data, 602 x 50, 8-bit/color RGBA, non-interlaced

So in this case the rounding issue does not occur. In developer tools it shows element-1 width as 602.328px and element-2 with as 296.656

I also tried to swap the elements from left to right and still everything worked fine.

**Comment by ishubin** [comment] 2015-11-18 09:21
Ah, got it :) It can be reproduced with width 50 % for both divs.

```
<div style="width:899px">
   <div class="tested" id="element-2" style="width:50%; background: green; float: left;">bar</div>
   <div class="tested" id="element-1" style="width:50%; background: red; float: right;">foo</div>
</div>
```

So I guess the problem is rounding of .5 px

**Comment by ishubin** [comment] 2015-11-18 09:26
@lo1tuma @timoreimann Ok so this is an interesting issue. What happens is this: both divs have width declared as 50%. But the container with is 899. So on the actual image they can't both get the same width. One of them has to sacrifice 1 px. And this is where things go wrong. The generated image samples are:

- element-1.png: PNG image data, 449 x 50, 8-bit/color RGBA, non-interlaced
- element-2.png: PNG image data, 450 x 50, 8-bit/color RGBA, non-interlaced

In developer tools their widths are shown as 449.5px.
I have no idea how to nicely fix this in Galen. Do you have any ideas? The only idea that I have - just allow to crop 1px by default. If it is more then one pixel - then you have to declare "crop-if-outside" property. What do you think?

**Comment by lo1tuma** [comment] 2015-11-18 11:32
Cropping 1px by default would a pragmatic solution :+1:.
At least for the page dump, when you create images, you have to drop the decimals somehow.

The webdriver spec explains how to [deal with floating point pixel values](http://www.w3.org/TR/webdriver/#dfn-normalize-style-pixel-values-to-floating-point) for the element displayedness but I’m not sure if this approach is really used in selenium.

**Comment by ishubin** [comment] 2015-11-18 11:51
Doing this on page dump level would not solve the issue. The actual problem we are dealing with is that it tries to get the subimage of the page element from a screenshot. The this subimage goes 1px further from the screenshot, which is caused by rounding the width.
I will implement 1px default crop and lets see how it goes

**Closed** 2015-11-29 19:41 UTC
Labels: bug, c3, p1, ready for test

**Comment by VladToporkov** [comment] 2019-03-14 12:29
Hi. I reproduce this issue too.
