### ISSUE TITLE
Correction does not work for object made by "multiple definition" 

### ISSUE THREAD

**Issue by ksiv** [galenframework/galen#526] opened 2017-10-20 16:51 UTC
`@objects`
` ....   menu                                       css    body>div.menu`
` ........       list  @(0, +6, 0, -12)             css    ul`
` ............           item*  @(0, +15, 0, -15)   css    li`
_#_ here two last rows of importance 
_#_ correction won't work for any "items"
_#_ works for "list" though

**Comment by hypery2k** [comment] 2017-10-21 16:02
so the correction is completely ignored?

**Comment by ksiv** [comment] 2017-10-23 08:11
@hypery2k, for elements mentioned -yes. I had to make `li:nth-child(N)` for each list item for correction to work. We use it broadly (up to 100% of spec) since we have a lot of texts.
Multiple definition itself works ok within one "ul", doesn't work for more complicated selection though.

**Comment by cyildirim** [comment] 2017-10-25 03:36
I reproduced that issue on my local and sent a fix about that. It looks like it is fixed after that change.

**Comment by ksiv** [comment] 2017-10-25 10:27
I tried your contribution localy - works for me. Could not predict any side-issues though as I build it with " -Dmaven.test.skip=true" :-)

**Comment by cyildirim** [comment] 2017-11-12 13:01
@ksiv  You can close this issue.

**Closed** 2017-11-13 13:41 UTC
