### ISSUE TITLE
Reports must generate JSON instead of HTML

### ISSUE THREAD

**Issue by operatino** [galenframework/galen#169] opened 2014-12-03 08:47 UTC
For the sake of flexibility, it's essential to provide raw report data, that could be then styled any way user wants.

**Comment by ishubin** [comment] 2015-02-21 09:18
Implemented in release-1.6 branch. At the moment it creates a "report.json" test overview report. And for each test separately it creates json detailed report. Also from now on html reporter is based on json reports. That makes it easier to maintain and improve

**Comment by hypery2k** [comment] 2015-02-21 20:06
There are some issues with rainbow4j see https://github.com/galenframework/rainbow4j/issues/2 and some of the browser tests are failing: https://martinreinhardt-online.de/jenkins/job/GalenFramework_integration/browser=chrome/2/console

**Comment by hypery2k** [comment] 2015-02-23 09:25
some feedback from production:
The report generation is working and looks great ;)
I'd like to add tag support. Are you currently done with the redesign?

Some minor remarks.

You renamed the method LayoutSpec.getErrorMessages() to LayoutSpec.getErrors(), any reason for that?

**Comment by ishubin** [comment] 2015-02-23 09:57
@hypery2k I don't really think there was any reason. Its just that I first came up with JSON I wanted to generate and then based on that renamed a lot of fields. Are there any problems on your project caused by this rename?

I am almost done with redesign. There still minor thing left but that is on the test report level. The report overview is finished. Basically you can work on that. We shouldn't have too much conflicts in this area. You can just implement tags as a list of strings (like in TestNG). This means that the "tags" will be presented in JSON test overview report. And based on that the html can also be rendered in two tabs: tests table as it is now and tags view. Do you have already some ideas on this?

**Comment by ishubin** [comment] 2015-02-23 10:36
@hypery2k 
>> If an element could not be found it would be nice to mark it in the report
As I understand you are describing the situation when element was not found in the DOM, right? But what we show in this case other than just a screenshot and an error?

>> Would be helpful to add a message to the JSON which shows up in the report for errors and passed checks
You mean like a list of errors in the layout report? I think it is a good idea. That will help to aggregate all errors in one place. Will implement that.

**Comment by hypery2k** [comment] 2015-02-23 13:15
No i mean when the locator is not found, see sample here:
![galen_report](https://cloud.githubusercontent.com/assets/979121/6328306/51c10ada-bb66-11e4-9d2d-c7d4ad23d66c.png)

**Comment by hypery2k** [comment] 2015-02-23 13:16
I will start with adding the tag support next week, this week I'm too busy for this. Maybe on the weekend

**Comment by ishubin** [comment] 2015-02-23 14:05
@hypery2k What you have shown on the screenshot is a bug. I will fix it. Thanks!

**Comment by hypery2k** [comment] 2015-02-23 14:41
thanks for that. I can retest and will add some tests later for that

**Comment by ishubin** [comment] 2015-02-23 19:24
@hypery2k  I have pushed the fix for absent objects.

**Comment by hypery2k** [comment] 2015-03-01 17:54
I've implemented basic tagging support for the reports:
![galen_tagged_reports](https://cloud.githubusercontent.com/assets/979121/6432040/01782774-c044-11e4-814b-615fa4909755.png)
The best of this is, it reuses the existing tags. So should be shown up automatically ;)

Next step should be to enabled grouping of tests, see above. So collapsing and expanding.

Additionally filtering of tags would be nice

**Comment by hypery2k** [comment] 2015-03-01 18:04
one remark: Besides the rendering of the JSON report data within the HTML we should add also a "pure" JSON output report file!

**Comment by ishubin** [comment] 2015-03-02 19:15
@hypery2k What do you mean by "pure" JSON output? At the moment there is already an output of json report in release-1.6 branch https://github.com/galenframework/galen/blob/release-1.6/src/main/java/net/mindengine/galen/GalenMain.java#L356

you can just provide ```--jsonreport path/to/json/report``` arguments in command line

do you want something else there?

**Comment by hypery2k** [comment] 2015-03-04 00:02
I mean just store a plain .json file in the report directory

**Comment by ishubin** [comment] 2015-03-04 08:33
Ah, ok. I think it is a good idea

**Closed** 2015-03-22 09:37 UTC
Labels: c2, enhancement, p3, ready for test
