### ISSUE TITLE
Java Unit Tests do not fail if a custom rule fails

### ISSUE THREAD

**Issue by TSwifts** [galenframework/galen#324] opened 2015-09-29 09:15 UTC
Hi,
while experimenting with Galen, I stumbled across the following behavior:

I am using the custom rule "should be squared" from your website (http://galenframework.com/docs/reference-galen-spec-language-guide/). Intentionally I wanted it to fail when using it on a defined object. And indeed in the generated HTML report I was able to see the (expected) error. However the corresponding Java unit test didn't fail and reported no error/failure. Surprised by this behavior I extracted the rule into a separate file and imported it for usage. I was able to observe the same behavior.
To validate that I didn't break anything I replaced the call of the custom rule with the mere line of code used in the custom rule. In this case the unit test behaved as I expected and reported the failure.
The Java unit test I wrote does nothing else than loading the website and checking the layout according to the spec file. The test class extends the class "GalenTestBase", copied from your Java sample tests.

I am using the following environment:
Linux Mint 17.1
JDK 1.8.0_60
Galen 2.1.0
TestNG 6.9.6
Firefox 41 (for Linux Mint)

**Comment by ishubin** [comment] 2015-09-29 09:31
Will check later, but first idea that comes to mind that the LayoutReport object contains incorrect information about the amount of errors in layout.

**Comment by TSwifts** [comment] 2015-09-29 09:35
Thanks for the very quick response! Sounds good to me, though so far I didn't take a look "under the hood" of Galen. Maybe I'll do that later. ;)

By the way, I forgot to mention that I am using Intellij IDEA 15 (Early Access Preview). But don't believe that this is the cause of the problem, despite the fact it is an EAP.

**Comment by ishubin** [comment] 2015-09-29 09:41
@TSwifts no, I don't think so. What you described in your original post, gave me some clues. Because I had similar bug before. But I am not sure. First of all I will have to reproduce it of course.

**Comment by ishubin** [comment] 2015-09-29 20:06
I have pushed a fix for this issue. It appeared that it is only reproduced for object-based custom rules. Basically the rules that are applied to a specific object. If you are interested in code, then here is the diff https://github.com/galenframework/galen/commit/3fc9271e9087878678da45da2ac41144be10a653  
As you can see it just din't care about ValidationResult :)

Thanks for reporting!
I have released it to maven central but it might take few hours before you get it as dependency.

**Closed by ishubin** 2015-09-29 20:06 UTC

**Comment by TSwifts** [comment] 2015-09-29 20:30
Wow! That was incredibly fast, thank you so much for your amazing work and in general for making Galen!
As soon as I arrive at work tomorrow, I will have a deeper look into it. ;)
