### ISSUE TITLE
Report from iframe component not showing details (rel 2.4)

### ISSUE THREAD

**Issue by pcieslak** [galenframework/galen#601] opened 2018-12-05 13:15 UTC
Before 2.4, all errors from component in iframe were shown on the report.
Currently there is only summary info on issues#...
![image](https://user-images.githubusercontent.com/18451235/49515700-f640eb80-f897-11e8-8a69-1ea51156b22b.png)

Can it be fixed to work as on ver < 2.4 ?

**Comment by ZeleniiZmey** [comment] 2019-01-29 11:04
Any update on this?

**Comment by ishubin** [comment] 2019-01-29 21:22
I am currently working on it but it appeared a bit more complicated than I thought. Might take some time since I totally overlooked sublayouts in components specs.

**Comment by ishubin** [comment] 2019-01-30 22:38
I have released a fix in v 2.4.2. Could you please check it?

**Comment by pcieslak** [comment] 2019-01-30 23:18
Looks fine - after quick check. If anything will be wrong - will reply by end of this week.

**Comment by pcieslak** [comment] 2019-02-04 15:11
after some time of usage, I found a case when it is not working. When component partially fails/partially passes. See screenshot
![image](https://user-images.githubusercontent.com/18451235/52216859-82bb5a80-2897-11e9-979b-98b5d2631b76.png)

**Comment by ishubin** [comment] 2019-02-04 15:59
@pcieslak Strange, looks like the spec "centered all inside asyncButton 12px" is not rendered in the report at all. I will try to reproduce it.

**Comment by pcieslak** [comment] 2019-02-07 13:51
@ishubin - it looks like it is not showing rules result.

**Comment by ishubin** [comment] 2019-02-11 20:19
@pcieslak I tried to reproduce but for me it did work correctly

<img width="1107" alt="screen shot 2019-02-11 at 21 13 49" src="https://user-images.githubusercontent.com/949577/52590613-05b55580-2e42-11e9-9bf4-b3def9ac06db.png">

**Comment by ishubin** [comment] 2019-02-11 20:20
Here is the sample project I used for reproducing the issue
[galen-issue-601.zip](https://github.com/galenframework/galen/files/2852905/galen-issue-601.zip)

**Comment by ZeleniiZmey** [comment] 2019-02-12 09:41
Ok. Issue is reproducible, when rule failed. I've just updated main.gspec and run your project against it.
```
@objects
    header      h3
    link        a


@rule %{name} should be clickable
    ${name}:
        height 2 to 50px

@rule above link should be %{from} to %{to}
        above link ${from} to ${to}px

= Inside frame test =
    header:
        | above link should be 5 to 10
        height 2 to 45px

    | header should be clickable
```

Here is the output:
![screen](https://user-images.githubusercontent.com/10129917/52626070-b1968980-2eb2-11e9-9b30-c752b38573d8.png)

**Comment by ishubin** [comment] 2019-02-17 22:29
Thanks for reporting it @ZeleniiZmey I actually missed those completely in the new report implementation. I have pushed and released a fix in 2.4.3

**Comment by ZeleniiZmey** [comment] 2019-02-18 12:23
It is ok now. Looks like we can close the issue. Many thanks.

**Closed** 2019-02-18 12:24 UTC
Labels: bug
