### ISSUE TITLE
Galen with JUnit on Jenkins

### ISSUE THREAD

**Issue by chrishelgert** [galenframework/galen#439] opened 2016-09-21 06:38 UTC
java version: 1.8.0.51
galen version: 2.3.0
used browser: Chrome

we are running our galen-tests via GalenJUnitTestBase and running them with surefire:test (mvn 3.3.3, surefire 2.19.1).

on the lokal machine (win10) everything works as expected.
on the jenkins all tests are running without a problem

> Results :
> 
> Tests run: 16, Failures: 0, Errors: 0, Skipped: 0

 but when the reporter try to generate the report follow error occurs:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-cli) on project common: Exception in provider: java.lang.RuntimeException: java.io.IOException: Directory 'target/galen-html-reports' could not be created.

if we look at the target-folder then there is already a galen-html-reports-folder:
drwxr-xr-x  2 jenkins jenkins    4096 21. Sep 08:17 galen-html-reports

any suggestions?

**Comment by hypery2k** [comment] 2016-09-21 07:06
did you clean before running in jenkins? You can look at my sample project [here](https://github.com/hypery2k/galen_samples/tree/master/junit) and a sample jenkins [job](https://martinreinhardt-online.de/jenkins/job/Galen/job/Galen_sample_JUnit/). Maybe this helps

**Comment by chrishelgert** [comment] 2016-09-21 07:26
yes we make a mvn clean before starting the galen-tests.
before the galeln-tests the target is complete empty. 
it looks like he is trying to create the folder multiple times

**Comment by ishubin** [comment] 2016-09-21 07:41
@chrishelgert Could you please post complete stacktrace of that exception? It shouldn't matter if the folder is created or not. Galen is supposed to auto-create it in case it is not there. Normally such issues occur in case the user doesn't have the proper rights. Not sure why it fails in your case

**Comment by hypery2k** [comment] 2016-09-21 07:46
Didn't know much about your current setup, but looks a bit strange for me as my sample project also uses the JunitTestBase

**Comment by opx3** [comment] 2016-09-21 07:54
Hi, the rights for the users are correct, because it creates the folder within the jenkins-job.
But directly after creating the galen-report-html folder it throws the exception "java.io.IOException: Directory 'target/galen-html-reports' could not be created"

**Comment by ishubin** [comment] 2016-09-21 08:00
@opx3 But can you share the stacktrace?

**Comment by opx3** [comment] 2016-09-21 08:24
I am running the job with -X at the moment. this will last a few moments.

**Comment by opx3** [comment] 2016-09-21 08:41
@ishubin i think the relevant part of the exception is this one, which is immediately thrown, after the folder galn-html-reports is created:
Caused by: java.io.IOException: Directory 'target/galen-html-reports' could not be created
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:363)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1928)
	at org.apache.commons.io.FileUtils.writeStringToFile(FileUtils.java:1962)
	at com.galenframework.reports.HtmlReportBuilder.build(HtmlReportBuilder.java:50)
	at com.galenframework.junit.JUnitStepListener.testRunFinished(JUnitStepListener.java:48)
	... 49 more

**Comment by ishubin** [comment] 2016-09-21 08:52
@opx3 Thanks, seems like a very weird behavior of apache-commons-io library. I will try to find a workaround for it and release a new build.

**Comment by opx3** [comment] 2016-09-21 15:44
@ishubin seems like the problem is at codeline 72 in HtmlReportBuilder.java:
FileUtils.forceMkdir(new File(reportFolderPath));

This should follow a  FileUtils.waitFor(File file, int seconds) afterwards.

For me it looks like it's a nfs-based problem.

**Comment by ishubin** [comment] 2016-09-22 06:52
@opx3 @chrishelgert I have released 2.3.1 with the fix. Could you please try it out?

**Comment by chrishelgert** [comment] 2016-09-22 10:53
@ishubin same problem but with a different stacktrace, we are currently trying to locate the problem

**Comment by danielbayerlein** [comment] 2016-09-29 07:58
Is there any news? Thanks for your support!

**Comment by ishubin** [comment] 2016-09-29 08:53
@danielbayerlein I am not aware. @opx3 told me that he was going to check it. If I understood correctly it was  some problem on the Jenkins machine side.

**Comment by danielbayerlein** [comment] 2016-09-29 10:53
@ishubin Thanks for your quick reply!

**Comment by opx3** [comment] 2016-10-13 16:11
@ishubin we finally figured out where the problem came from.
And first: it's not a galen problem.

It's based on a very strange behaviour of maven and dependency handling, when building multi-dependant projects.
I will investigate the maven code and'll try to find out, where this problem exactly comes from.

If some has a structure that looks like this:
- MainProject with pom.xml
| - SubProject 1
| - - Pom.xml in Subproject 1 WITH GalenTests
| - SubProject 2
| - - Pom.xml in Subproject 2
| - SubProject 3
| - - Pom.xml in Subproject 3

AND if it's nessesary to build all 3 projects first and after that execute the tests in "SubProject 1", maven will fail, because it seeems as if maven looses the path to "SubProject 1".

Our Solution:
We first let maven build the MainProject, which included all SubProjects.
Afterwards we explicitly started maven again in the "SubProject 1" folder to exceute the tests.
And this way worked.

From my point of view you can close this issue.

Regards

px3

**Comment by ishubin** [comment] 2016-10-14 07:45
@opx3 Thanks for explanation!

**Closed by ishubin** 2016-10-14 07:45 UTC
