### ISSUE TITLE
TestNG memory leak

### ISSUE THREAD

**Issue by kalumpiwarra** [galenframework/galen#477] opened 2017-02-20 08:34 UTC
Hi!

I'm using galen framework for image comparison (big amount of templates). 
I faced with memory leaks when most of my tests failed. Error: OutOfMemoryError exception.
I reproduced it locally and I got the following picture:
![default](https://cloud.githubusercontent.com/assets/15207334/23117057/090bce24-f778-11e6-9654-110539827212.png)
Used heap is constantly growing.
After investigation, I figured out that 'ValidationError' object doesn't released and brings such memory leak.
All validation results (BufferedImages) stored till the end of testNG run.

At the moment I release ValidationError at the @AfterMethod.

Can it be fixed inside of framework?
Could you please take a look?

**Comment by ishubin** [comment] 2017-02-20 12:02
Thanks for your investigation! I will take a look at it.

**Comment by ishubin** [comment] 2017-02-20 13:12
Could you please clarify some things for me, so that I get a better picture of this problem. How does it work in your case? Are you executing galen tests in TestNG and in the end it generates a large HTML report? How many images do you have? I just wonder how come you get 3.5 GB. 

Correct me if I am wrong: the problem is actually not the memory leak. The real problem is the unoptimized data structure of ValidationError object. It basically keeps all the pixels of the images in memory and since you have a lot of tests - it just eats a lot of memory.
If I got the problem correctly I think I can solve it in the current version 2.3.
I, potentially see two problems here that should be solved, but we can start with the first one and already win a lot in terms of memory usage. 

1) Change BufferedImage fields to File handles,  which would point to temp image files   (https://github.com/galenframework/galen/blob/master/galen-core/src/main/java/com/galenframework/validation/ImageComparison.java#L21). The only downside in this case is that it would eat a lot of disk space.
 
2) Optimize reports generation. When the test is finished galen should not keep the complete test report in memory, but rather export it already to all report folders and cleanup all temp files generated by this test. In the end of the test suite it would only need to export overview report (json, html).

**Comment by kalumpiwarra** [comment] 2017-02-20 14:00
Actually for me problem only that GalenTestInfo doesn't clean up ValidationError (which contains Original/Sample/Comparison objects as BufferedImage) after test finished.
During test run I'm using this ValidationError and I like that I have direct access to BufferedImage from LayoutReport.
As far as I can see, Galen has stores images on the disc (for me it's %TEMP% Windows directory) during test run and copies it to the report directory at the end. So for now images are stored the disk and at memory.

My idea is to have access to BufferedImage during test run and release it during test tear down and store only links to file system.

In my particular case I'm performing a lot of verifications against images. For example each test verify 6 images in 3 resolutions, that's the reason of such big memory usage.

Sorry if I'm not clear explain an idea.
P.S. Thanks a lot for such great tool!

**Comment by ishubin** [comment] 2018-04-02 20:06
Fixed in `release-2.4` branch

**Closed** 2018-04-02 20:06 UTC
Labels: bug, c2, p3, ready for test
